name: smooth_api
description: This library utilises Dart internal isolate to handle all your network calls to Api and on top of that it uses Hive database to cache the api responses and will give the response back even when internet is not available.
version: 1.0.0
homepage: https://github.com/AnonymousAliensX/SmoothApi
maintainer: Sawan Sihag (@InvincibleSihag)

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  hive: ^2.2.3
  crypto: ^3.0.2
  http: ^0.13.5
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
